execom-eu/hawaii

- src/main/frontend/public/index.html
- src/main/frontend/src/components/common/NavigationLink.js
- src/main/frontend/src/components/common/ShadowRow.js
- src/main/frontend/src/components/common/UserImage.js
- src/main/frontend/src/components/header/InformationHeader.js
- src/main/frontend/src/components/navigation/NavBar.js
- src/main/frontend/src/components/navigation/Sidebar.js
- src/main/frontend/src/index.js
- src/main/frontend/src/pages/ExecomCalendar.js
- src/main/frontend/src/pages/Leave.js
- src/main/frontend/src/pages/LeaveHistory.js
- src/main/frontend/src/pages/Login.js
- src/main/frontend/src/pages/TeamCalendar.js
- src/main/frontend/src/styles/globalStyles.js
> F feature/component merging branch

- src/main/java/eu/execom/hawaii/api/controller/TeamController.java
- src/main/java/eu/execom/hawaii/dto/TeamDto.java
- src/main/java/eu/execom/hawaii/repository/TeamRepository.java
- src/main/java/eu/execom/hawaii/service/TeamService.java
> B feature/team management

- src/main/java/eu/execom/hawaii/api/controller/LeaveProfileController.java
- src/main/java/eu/execom/hawaii/dto/LeaveProfileDto.java
- src/main/java/eu/execom/hawaii/repository/LeaveProfileRepository.java
- src/main/java/eu/execom/hawaii/service/LeaveProfileService.java
> B feature/leave profile management

- README.md
- pom.xml
- src/main/java/eu/execom/hawaii/security/SecurityConfiguration.java
> Added swagger

- src/main/java/eu/execom/hawaii/api/controller/UserController.java
- src/main/java/eu/execom/hawaii/repository/UserRepository.java
- src/main/java/eu/execom/hawaii/service/UserService.java
- src/main/resources/application.properties
- src/test/java/eu/execom/hawaii/service/EntityBuilder.java
- src/test/java/eu/execom/hawaii/service/UserServiceTest.java
> B test/user service tests

- src/main/java/eu/execom/hawaii/api/controller/UserController.java
- src/main/java/eu/execom/hawaii/repository/UserRepository.java
- src/main/java/eu/execom/hawaii/service/UserService.java
- src/main/resources/application.properties
- src/test/java/eu/execom/hawaii/service/EntityBuilder.java
- src/test/java/eu/execom/hawaii/service/TeamServiceTest.java
- src/test/java/eu/execom/hawaii/service/UserServiceTest.java
> B test/team service test

- src/main/java/eu/execom/hawaii/service/GoogleCalendarService.java
- src/main/java/eu/execom/hawaii/service/RequestService.java
> B feature/calendar pending event

- src/main/java/eu/execom/hawaii/dto/RequestDto.java
enabled getting the submission time for requests
> fixed requestDto mapping

- src/main/java/eu/execom/hawaii/service/RequestService.java
> Added check on request creation with already existing requests status

- pom.xml
- src/main/java/eu/execom/hawaii/service/SendNotificationsService.java
- src/main/resources/application.properties
- src/test/java/eu/execom/hawaii/service/RequestServiceTest.java
Removed unnecessary code, fixed tests.
> B fix/request service tests

- src/main/java/eu/execom/hawaii/dto/UserDto.java
In agreement with the mobile team, beside team name we also provide team id in UserDto.
> Team name and team id in userDto.

- src/main/java/eu/execom/hawaii/repository/UserPushTokensRepository.java
- src/main/java/eu/execom/hawaii/service/UserService.java
First, checks if the exact same push token for authenticated user already exists.
If it doesn't exist, create new UserPushToken and return the new UserPushToken.
If already exists, just pass him through and return the old UserPushToken.
> B fix/check if push token already exists

- src/main/java/eu/execom/hawaii/dto/UserDto.java
- src/main/java/eu/execom/hawaii/jobs/CarryOverVacationJob.java
- src/main/java/eu/execom/hawaii/model/User.java
- src/main/java/eu/execom/hawaii/service/EmailService.java
- src/main/java/eu/execom/hawaii/service/UserService.java
- src/main/java/eu/execom/hawaii/util/EmailSubjectProvider.java
- src/main/resources/db/changelog/initialDbSchema.xml
- src/main/resources/templates/userLeaveProfileUpdate.ftl
- src/test/java/eu/execom/hawaii/jobs/CarryOverVacationJobTest.java
- src/test/java/eu/execom/hawaii/jobs/IncrementServiceYearsJobTest.java
- src/test/java/eu/execom/hawaii/service/AllowanceServiceTest.java
- src/test/java/eu/execom/hawaii/service/EntityBuilder.java
- src/test/java/eu/execom/hawaii/service/RequestServiceTest.java
- src/test/java/eu/execom/hawaii/service/UserServiceTest.java
- src/test/java/eu/execom/hawaii/service/YearServiceTest.java
StartedWorkingDate, and StartedWorkingAtExecomDate fields added to User
> B fix/user add start working day

- src/test/java/eu/execom/hawaii/service/AbsenceServiceTest.java
- src/test/java/eu/execom/hawaii/service/DayServiceTest.java
- src/test/java/eu/execom/hawaii/service/LeaveProfileServiceTest.java
- src/test/java/eu/execom/hawaii/service/TeamServiceTest.java
Fixed tests after your reviews
> Test Add - Fixed

- src/main/java/eu/execom/hawaii/api/controller/AllowanceController.java
method name changed to avoid method overloading
> method name changed

- src/main/java/eu/execom/hawaii/service/RequestService.java
- src/test/java/eu/execom/hawaii/service/RequestServiceTest.java
Request can be cancelled only by user who made it.
> Fixes request cancellation

- src/main/java/eu/execom/hawaii/dto/RequestDto.java
- src/main/java/eu/execom/hawaii/model/Absence.java
- src/main/java/eu/execom/hawaii/model/Request.java
- src/main/java/eu/execom/hawaii/model/User.java
- src/main/java/eu/execom/hawaii/service/RequestService.java
- src/main/resources/db/changelog/initialDbSchema.xml
- bonus request needs to be approved by all team approvers from users team
> Handle bonus request approval

- src/main/frontend/src/pages/EditTeam.js
Fixed employee search in team edit
> f-fix/team-edit-employee-search-dropdown

- src/main/java/eu/execom/hawaii/api/controller/UserController.java
- src/main/java/eu/execom/hawaii/service/UserService.java
- src/test/java/eu/execom/hawaii/service/UserServiceTest.java
Calculate years of service from first employment date to date of employment in Execom and set it for created user.
GH issue #226
> B-fix/gh-226-set-yearsOfService-for-created-user

- src/main/frontend/src/components/leave-types/LeaveTypeItem.js
- src/main/frontend/src/components/leave-types/LeaveTypes.js
- src/main/frontend/src/layout/Panel.js
- src/main/frontend/src/pages/Administration.js
- src/main/frontend/src/pages/CreateLeaveType.js
- src/main/frontend/src/pages/EditLeaveType.js
- src/main/frontend/src/pages/LeaveType.js
- src/main/frontend/src/store/actions/leaveTypeActions.js
- src/main/frontend/src/store/reducers/leaveTypeReducer.js
- src/main/frontend/src/store/reducers/reducers.js
- src/main/frontend/src/store/sagas/leaveTypeSaga.js
- src/main/frontend/src/store/sagas/sagas.js
- src/main/frontend/src/store/selectors.js
- src/main/frontend/src/store/services/leaveTypeService.js
Created CRUD for leave types
GH issue: #241
> f-feature/gh-241-leave-types-crud

- src/main/frontend/src/components/years/YearItem.js
- src/main/frontend/src/components/years/Years.js
- src/main/frontend/src/layout/Panel.js
- src/main/frontend/src/pages/Administration.js
- src/main/frontend/src/pages/CreateYear.js
- src/main/frontend/src/pages/EditYear.js
- src/main/frontend/src/pages/Year.js
- src/main/frontend/src/store/actions/yearActions.js
- src/main/frontend/src/store/actions/yearsActions.js
- src/main/frontend/src/store/reducers/reducers.js
- src/main/frontend/src/store/reducers/yearReducer.js
- src/main/frontend/src/store/reducers/yearsReducer.js
- src/main/frontend/src/store/sagas/sagas.js
- src/main/frontend/src/store/sagas/yearSaga.js
- src/main/frontend/src/store/sagas/yearsSaga.js
- src/main/frontend/src/store/selectors.js
- src/main/frontend/src/store/services/yearService.js
- src/main/frontend/src/store/services/yearsService.js
Created years CRUD.
GH Issue: #239
> f-feature/gh-239-years-crud

- src/main/java/eu/execom/hawaii/repository/UserRepository.java
- src/main/java/eu/execom/hawaii/service/UserService.java
- src/test/java/eu/execom/hawaii/service/RequestServiceTest.java
- src/test/java/eu/execom/hawaii/service/UserServiceTest.java
- check if user with given e-mail already exists in database
- if user exists throw entity exists exception
> Check if user exists when creating new user

- src/main/java/eu/execom/hawaii/repository/TeamRepository.java
- src/main/java/eu/execom/hawaii/service/TeamService.java
- src/test/java/eu/execom/hawaii/service/TeamServiceTest.java
- if team exists throw entity exists exception
> Check if team with given name already exists when creating new team

- src/main/java/eu/execom/hawaii/dto/AllowanceWithoutYearDto.java
> Allowance without year dto attributes refactoring

- src/main/java/eu/execom/hawaii/api/controller/AllowanceController.java
- src/main/java/eu/execom/hawaii/service/AllowanceService.java
Added endpoint in AllowanceController to return all years for which authenticated user has allowance
Gh issue: #249
> B-feture/gh-249-return-all-years-with-allowance-for-given-user
